[package]
name = "bearer_link_x"
type = "bin"
authors = ["libID"]
compiler_version = ">=1.0.0"

[dependencies]
libid_identity = { path = "../../lib/identity" }
libid_identity_testing = { path = "../../lib/identity-testing" }
